"""Generates src/pyanypia/params/_data2026.py from the paramdump goldens.

The paramdump tool (oracle/instrumented/paramdump.cpp) exports PiaParamsAny's
assembled series per assumption alternative. Historical portions are
identical across alternatives (asserted here); projected portions are stored
per alternative as the assumption paths (fqinc, cpiinc).

Historical boundaries follow awbidtnf.cpp (2026 TR):
  fq (AWI)        1937-2024
  cpiinc (COLA)   1951-2025
  base_oasdi      1937-2026
  base_77         1937-2026
  base_hi         1991-2026   (pre-1991 equals base_oasdi)
  qc_amt          1978-2026   (pre-1978 QCs are not amount-based)
  yoc_amt_specmin 1937-2026   (special-minimum year-of-coverage amounts)

Run: python3 oracle/tools/extract_data.py
"""

from __future__ import annotations

import json
import pathlib

ORACLE = pathlib.Path(__file__).resolve().parent.parent
OUT = ORACLE.parent / "src" / "pyanypia" / "params" / "_data2026.py"

HIST_RANGES = {
    "fq": (1937, 2024),
    "cpiinc": (1951, 2025),
    "base_oasdi": (1937, 2026),
    "base_77": (1937, 2026),
    "base_hi": (1991, 2026),
    "qc_amt": (1978, 2026),
    "yoc_amt_specmin": (1937, 2026),
}


def main() -> None:
    dumps = {
        alt: json.load(open(ORACLE / "goldens" / f"params_alt{alt}.json"))
        for alt in (1, 2, 3)
    }
    maxyear = dumps[2]["maxyear"]
    istart = dumps[2]["istart"]
    assert istart == 2026, istart

    hist: dict[str, dict[int, float]] = {}
    for key, (y0, y1) in HIST_RANGES.items():
        series: dict[int, float] = {}
        for y in range(y0, y1 + 1):
            vals = {
                alt: dumps[alt]["years"][str(y)][key] for alt in (1, 2, 3)
            }
            assert len(set(vals.values())) == 1, (
                f"{key}[{y}] differs across alternatives: {vals}"
            )
            v = vals[2]
            assert v is not None, f"{key}[{y}] is null"
            series[y] = v
        hist[key] = series

    # Projected assumption paths per alternative. fqinc[y] is the AWI
    # percentage increase for year y (fq[y] = fq[y-1]*(1+fqinc[y]/100));
    # cpiinc[y] is the December benefit increase.
    proj: dict[str, dict[int, dict[int, float]]] = {"fqinc": {}, "cpiinc": {}}
    for alt in (1, 2, 3):
        yrs = dumps[alt]["years"]
        proj["fqinc"][alt] = {
            y: yrs[str(y)]["fqinc"]
            for y in range(2025, maxyear + 1)
            if yrs[str(y)]["fqinc"] is not None
        }
        proj["cpiinc"][alt] = {
            y: yrs[str(y)]["cpiinc"]
            for y in range(2026, maxyear + 1)
            if yrs[str(y)]["cpiinc"] is not None
        }

    # Historical fqinc (percent increases through 2024, istart-2) is derived
    # data in the C++ (set via setHistFqinc); keep 2025's value per-alt only.
    lines: list[str] = []
    lines.append('"""GENERATED by oracle/tools/extract_data.py — do not edit.')
    lines.append("")
    lines.append("Historical Social Security law parameters, 2026 Trustees")
    lines.append("Report edition, extracted from the compiled AnyPIA oracle")
    lines.append('(which embeds awbidtnf.cpp / assumption data)."""')
    lines.append("")
    lines.append(f"ISTART = {istart}")
    lines.append(f"MAXYEAR = {maxyear}")
    lines.append("")
    for key, series in hist.items():
        y0, y1 = HIST_RANGES[key]
        lines.append(f"# {key}: {y0}-{y1}")
        lines.append(f"{key.upper()}_FIRST = {y0}")
        lines.append(f"{key.upper()} = (")
        for y in range(y0, y1 + 1):
            lines.append(f"    {series[y]!r},  # {y}")
        lines.append(")")
        lines.append("")
    for key in ("fqinc", "cpiinc"):
        for alt in (1, 2, 3):
            d = proj[key][alt]
            y0 = min(d)
            lines.append(f"# projected {key}, alternative {alt}: {y0}-{max(d)}")
            lines.append(f"{key.upper()}_PROJ_ALT{alt}_FIRST = {y0}")
            lines.append(f"{key.upper()}_PROJ_ALT{alt} = (")
            for y in sorted(d):
                lines.append(f"    {d[y]!r},  # {y}")
            lines.append(")")
            lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    n = sum(len(s) for s in hist.values()) + sum(
        len(d) for k in proj.values() for d in k.values()
    )
    print(f"wrote {OUT} ({n} values)")


if __name__ == "__main__":
    main()
