"""Generates src/pyanypia/params/_data2026.py from the paramdump goldens.

The paramdump tool (oracle/instrumented/paramdump.cpp) exports PiaParamsAny's
assembled series per assumption alternative. Historical portions are
identical across alternatives (asserted here); projected portions are stored
per alternative as the assumption paths (fqinc, cpiinc).

Historical boundaries follow awbidtnf.cpp (2026 TR):
  fq (AWI)        1937-2024
  cpiinc (COLA)   1951-2025
  base_oasdi      1937-2026
  base_77         1937-2026
  base_hi         1991-2026   (pre-1991 equals base_oasdi)
  qc_amt          1978-2026   (pre-1978 QCs are not amount-based)
  yoc_amt_specmin 1937-2026   (special-minimum year-of-coverage amounts)

The 1950s PIB conversion tables are static arrays in the C++ rather than
anything paramdump computes, so they are parsed straight out of the vendored
piadata/pib*.cpp with their lengths asserted against the bounds checks in
each file's getAt().

Run: python3 oracle/tools/extract_data.py
"""

from __future__ import annotations

import json
import pathlib
import re

ORACLE = pathlib.Path(__file__).resolve().parent.parent
OUT = ORACLE.parent / "src" / "pyanypia" / "params" / "_data2026.py"
PIADATA = ORACLE / "vendor" / "oactobjs32" / "piadata"

HIST_RANGES = {
    "fq": (1937, 2024),
    "cpiinc": (1951, 2025),
    "base_oasdi": (1937, 2026),
    "base_77": (1937, 2026),
    "base_hi": (1991, 2026),
    "qc_amt": (1978, 2026),
    "yoc_amt_specmin": (1937, 2026),
}

# (emitted name, source file, C++ qualified symbol, length per getAt bounds)
PIB_TABLES = [
    ("PIB50_PIB", "pib50pib.cpp", "Pib50Pib::pib50", 486),
    ("PIB50_MFB", "pib50mfb.cpp", "Pib50Mfb::mfb50", 486),
    ("PIB52_AME", "pib52ame.cpp", "Pib52Ame::ame52", 206),
    ("PIB52_MFB", "pib52mfb.cpp", "Pib52Mfb::mfb52", 486),
    ("PIB54_AME", "pib54ame.cpp", "Pib54Ame::ame54", 196),
    ("PIB54_MFB", "pib54mfb.cpp", "Pib54Mfb::mfb54", 486),
    ("PIB54_PIA", "pib54pia.cpp", "Pib54Pia::pia54", 157),
    ("PIB58_AME", "pib58ame.cpp", "Pib58Ame::ame58", 63),
    ("PIB58_PIB", "pib58pib.cpp", "Pib58Pib::pib58", 63),
]

_NUMBER = re.compile(r"-?\d+\.?\d*(?:[eE][-+]?\d+)?")


def parse_cpp_array(filename: str, symbol: str, expected: int) -> list[float]:
    """Parses `const double <symbol>[] = { ... };` out of a vendored file."""
    text = (PIADATA / filename).read_text()
    start = text.index(f"{symbol}[] = {{") + len(f"{symbol}[] = {{")
    body = text[start:text.index("};", start)]
    body = re.sub(r"//[^\n]*", "", body)
    values = [float(m.group()) for m in _NUMBER.finditer(body)]
    if len(values) != expected:
        raise SystemExit(
            f"{filename}: {symbol} has {len(values)} values, expected "
            f"{expected} (getAt bounds check disagrees with the initializer)"
        )
    return values


def main() -> None:
    dumps = {
        alt: json.load(open(ORACLE / "goldens" / f"params_alt{alt}.json"))
        for alt in (1, 2, 3)
    }
    maxyear = dumps[2]["maxyear"]
    istart = dumps[2]["istart"]
    assert istart == 2026, istart

    hist: dict[str, dict[int, float]] = {}
    for key, (y0, y1) in HIST_RANGES.items():
        series: dict[int, float] = {}
        for y in range(y0, y1 + 1):
            vals = {
                alt: dumps[alt]["years"][str(y)][key] for alt in (1, 2, 3)
            }
            assert len(set(vals.values())) == 1, (
                f"{key}[{y}] differs across alternatives: {vals}"
            )
            v = vals[2]
            assert v is not None, f"{key}[{y}] is null"
            series[y] = v
        hist[key] = series

    # Projected assumption paths per alternative. fqinc[y] is the AWI
    # percentage increase for year y (fq[y] = fq[y-1]*(1+fqinc[y]/100));
    # cpiinc[y] is the December benefit increase.
    proj: dict[str, dict[int, dict[int, float]]] = {"fqinc": {}, "cpiinc": {}}
    for alt in (1, 2, 3):
        yrs = dumps[alt]["years"]
        proj["fqinc"][alt] = {
            y: yrs[str(y)]["fqinc"]
            for y in range(2025, maxyear + 1)
            if yrs[str(y)]["fqinc"] is not None
        }
        proj["cpiinc"][alt] = {
            y: yrs[str(y)]["cpiinc"]
            for y in range(2026, maxyear + 1)
            if yrs[str(y)]["cpiinc"] is not None
        }

    # Historical fqinc (percent increases through 2024, istart-2) is derived
    # data in the C++ (set via setHistFqinc); keep 2025's value per-alt only.
    lines: list[str] = []
    lines.append('"""GENERATED by oracle/tools/extract_data.py — do not edit.')
    lines.append("")
    lines.append("Historical Social Security law parameters, 2026 Trustees")
    lines.append("Report edition, extracted from the compiled AnyPIA oracle")
    lines.append('(which embeds awbidtnf.cpp / assumption data)."""')
    lines.append("")
    lines.append(f"ISTART = {istart}")
    lines.append(f"MAXYEAR = {maxyear}")
    lines.append("")
    for key, series in hist.items():
        y0, y1 = HIST_RANGES[key]
        lines.append(f"# {key}: {y0}-{y1}")
        lines.append(f"{key.upper()}_FIRST = {y0}")
        lines.append(f"{key.upper()} = (")
        for y in range(y0, y1 + 1):
            lines.append(f"    {series[y]!r},  # {y}")
        lines.append(")")
        lines.append("")
    for key in ("fqinc", "cpiinc"):
        for alt in (1, 2, 3):
            d = proj[key][alt]
            y0 = min(d)
            lines.append(f"# projected {key}, alternative {alt}: {y0}-{max(d)}")
            lines.append(f"{key.upper()}_PROJ_ALT{alt}_FIRST = {y0}")
            lines.append(f"{key.upper()}_PROJ_ALT{alt} = (")
            for y in sorted(d):
                lines.append(f"    {d[y]!r},  # {y}")
            lines.append(")")
            lines.append("")

    # 1950s PIB conversion tables, indexed from 0 (piadata/pib*.cpp).
    pib_total = 0
    for name, filename, symbol, expected in PIB_TABLES:
        values = parse_cpp_array(filename, symbol, expected)
        pib_total += len(values)
        lines.append(f"# {symbol} ({filename}), {expected} entries")
        lines.append(f"{name} = (")
        for i in range(0, len(values), 10):
            row = ", ".join(repr(v) for v in values[i:i + 10])
            lines.append(f"    {row},")
        lines.append(")")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    n = sum(len(s) for s in hist.values()) + sum(
        len(d) for k in proj.values() for d in k.values()
    ) + pib_total
    print(f"wrote {OUT} ({n} values, {pib_total} in PIB tables)")


if __name__ == "__main__":
    main()
